CC = gcc
CXX = g++
LD = $(CXX)

CFLAGS = -O3 -g -I../../include -fopenmp
CFLAGS += -DUSE_OMP
LDFLAGS = -lpthread -lm -fopenmp

LIBS =
OBJS = main.o algo.o compcpu.o
HDRS = 

APP = stencil
all: $(APP)

$(APP): $(OBJS)
	$(LD) $(OBJS) -o $@ $(LDFLAGS)

%.o : %.c $(HDRS)
	$(CC) $(CFLAGS) -c $< -o $*.o

%.o : %.cc $(HDRS)
	$(CXX) $(CFLAGS) -c $< -o $*.o

clean:
	rm -f *.o
	rm -f *~
	rm -f core
	rm -f core.*
	rm -f $(APP)
	rm -f a.out
