CC = gcc
CXX = g++
LD = $(CXX)

CFLAGS = -O3 -g -I../../include -fopenmp -march=native
# -O3
CFLAGS += -DUSE_AVX2
LDFLAGS = -lm -fopenmp

LIBS =
OBJS = matmul.o kernel-avx2.o
HDRS = 

APP = matmul
all: $(APP)

$(APP): $(OBJS)
	$(LD) $(OBJS) -o $@ $(LDFLAGS)

%.o : %.c $(HDRS)
	$(CC) $(CFLAGS) -c $< -o $*.o

%.o : %.cc $(HDRS)
	$(CXX) $(CFLAGS) -c $< -o $*.o

clean:
	rm -f *.o
	rm -f *~
	rm -f core
	rm -f core.*
	rm -f $(APP)
	rm -f a.out
