CC = gcc
CXX = g++
LD = $(CXX)

CFLAGS = -O3 -g -I../../include -fopenmp -march=native
#-mavx512f
#

CFLAGS += -DUSE_AVX512 -DUSE_OMP
LDFLAGS = -lm -fopenmp

LIBS =
OBJS = apsp.o algo.o  kernel-avx512.o
HDRS = 

APP = apsp
all: $(APP)

$(APP): $(OBJS)
	$(LD) $(OBJS) -o $@ $(LDFLAGS)

%.o : %.c $(HDRS)
	$(CC) $(CFLAGS) -c $< -o $*.o

%.o : %.cc $(HDRS)
	$(CXX) $(CFLAGS) -c $< -o $*.o

clean:
	rm -f *.o
	rm -f *~
	rm -f core
	rm -f core.*
	rm -f $(APP)
	rm -f a.out
